dataset: "BAMotifs"
data_path: "data"
log_path: "logs"

task_type: "classification"

conv_type: "NNConv"

num_layers: 4
hidden_channels: 64
use_norm: true
learning_rate: 0.0002
batch_size: 64
baseline_epochs: 100
explainer_epochs: 500

baseline_pretrained: null
explainer_pretrained: null

sparsity: 0.15
reward_coeff: 5.0

train_size: 0.8
val_size: 0.1
test_size: 0.1

logging: true
tb_logging: true
seed: 0

retrain_predictors: false

